// قاعدة تمارين شاملة لمحرك "المدرب الشخصي الذكي" في قسم الرياضة. كل تمرين
// مصنَّف بعضلة مستهدفة دقيقة (لا فئات عريضة كـ"دفع/سحب" كما في exercises.js
// القديم) + نوع (مركّب/عزل) + بيئة معدات متوافقة + مستوى صعوبة + المفاصل
// المتأثرة (لفلترة الإصابات) - محرّك fitness-engine.js يبني منها البرنامج.
//
// ملاحظة قانونية: كل المبادئ هنا (تقسيم العضلات، حجم التدريب، نطاقات
// التكرار) مبادئ علمية عامة متّفق عليها في علم التدريب (معرفة عامة غير
// محمية) - لا اسم مدرب أو برنامج تجاري مذكور أو منسوخ في أي مكان هنا.

// أربع بيئات معدات (نفس المفاتيح المستخدمة في fitness_profile.equipment
// القديم + بيئة رابعة جديدة home_full_equipment) - كل تمرين يحمل قائمة
// البيئات المتوافقة معه.
export const EQUIPMENT_ENVIRONMENTS = [
  { key: "gym", name: "نادي رياضي كامل", nameEn: "Full gym" },
  { key: "home_full_equipment", name: "منزل بمعدات كاملة", nameEn: "Home with full equipment" },
  { key: "home_light_weights", name: "منزل بأوزان بسيطة (دمبل)", nameEn: "Home with light weights (dumbbells)" },
  { key: "home_no_equipment", name: "منزل بدون معدات", nameEn: "Home, no equipment" },
];

export const FITNESS_GOALS = [
  { key: "lose_weight", name: "تنشيف (فقدان دهون)", nameEn: "Fat loss (cutting)" },
  { key: "build_muscle", name: "تضخيم (بناء عضل)", nameEn: "Muscle gain (bulking)" },
  { key: "general_fitness", name: "تحسين اللياقة العامة", nameEn: "Improve general fitness" },
  { key: "maintain_weight", name: "محافظة على الوزن", nameEn: "Maintain current weight" },
];

export const EXPERIENCE_LEVELS = [
  { key: "beginner", name: "مبتدئ", nameEn: "Beginner" },
  { key: "intermediate", name: "متوسط", nameEn: "Intermediate" },
  { key: "advanced", name: "متقدم", nameEn: "Advanced" },
];

export const SESSION_DURATIONS = [30, 45, 60, 90];

// مناطق إصابة/حساسية مفصلية - تُستخدَم لاستبعاد تمارين تُجهد المنطقة
// المصابة تلقائياً (انظر JOINT بأسفل كل تمرين) واستبدالها ببديل آمن.
export const INJURY_AREAS = [
  { key: "knee", name: "الركبة", nameEn: "Knee" },
  { key: "lower_back", name: "أسفل الظهر", nameEn: "Lower back" },
  { key: "shoulder", name: "الكتف", nameEn: "Shoulder" },
  { key: "wrist", name: "الرسغ", nameEn: "Wrist" },
  { key: "neck", name: "الرقبة", nameEn: "Neck" },
  { key: "hip", name: "الورك", nameEn: "Hip" },
  { key: "elbow", name: "المرفق", nameEn: "Elbow" },
];

// المجموعات العضلية الدقيقة (لا فئات عريضة) - تُستخدَم لحساب حجم التدريب
// الأسبوعي لكل عضلة وتوزيعه على تقسيم الأيام (split) في fitness-engine.js.
export const MUSCLE_GROUPS = [
  "chest", "back", "shoulders", "biceps", "triceps",
  "quads", "hamstrings", "glutes", "calves", "abs",
  "full_body", "cardio", "mobility",
];

// exercise: { id, name, nameEn, muscle, type: compound|isolation|cardio|mobility,
//   equipment: [...EQUIPMENT_ENVIRONMENTS keys], difficulty: beginner|intermediate|advanced,
//   joints: [...INJURY_AREAS keys] (فارغة إن كان التمرين آمناً لكل المفاصل تقريباً),
//   icon, description, descriptionEn }
export const EXERCISES = [
  // ===================== صدر (chest) =====================
  { id: "pushup", name: "تمرين الضغط", nameEn: "Push-up", muscle: "chest", type: "compound", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: ["wrist", "shoulder"], icon: "Dumbbell", description: "استلقِ على بطنك مع استقامة الجسم، ادفع بيديك حتى تمديد الذراعين بالكامل، ثم انزل ببطء حتى يقترب صدرك من الأرض.", descriptionEn: "Lie face down with your body straight, push with your arms until fully extended, then lower slowly until your chest nearly touches the ground." },
  { id: "incline_pushup", name: "ضغط مائل (سهل)", nameEn: "Incline push-up", muscle: "chest", type: "compound", equipment: ["home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: ["wrist"], icon: "Dumbbell", description: "ضع يديك على سطح مرتفع (كرسي أو طاولة) وقدميك على الأرض، وأدِّ حركة الضغط بزاوية أخف على الرسغين.", descriptionEn: "Place your hands on a raised surface with your feet on the ground, and perform the push-up at an angle that's easier on the wrists." },
  { id: "decline_pushup", name: "ضغط مائل (صعب)", nameEn: "Decline push-up", muscle: "chest", type: "compound", equipment: ["home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "intermediate", joints: ["wrist", "shoulder"], icon: "Dumbbell", description: "ضع قدميك على سطح مرتفع ويديك على الأرض، وأدِّ الضغط بزاوية أثقل تركّز على الصدر العلوي.", descriptionEn: "Place your feet on a raised surface with your hands on the ground, and perform the push-up at a steeper angle that emphasizes the upper chest." },
  { id: "db_floor_press", name: "ضغط الصدر بالدمبل من الأرض", nameEn: "Dumbbell floor press", muscle: "chest", type: "compound", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "beginner", joints: ["shoulder"], icon: "Dumbbell", description: "استلقِ على ظهرك مع دمبل بكل يد عند الصدر، وادفعهما لأعلى حتى استقامة الذراعين.", descriptionEn: "Lie on your back with a dumbbell in each hand at chest level, and push them up until your arms are fully extended." },
  { id: "db_bench_press", name: "ضغط الصدر بالدمبل على بنش", nameEn: "Dumbbell bench press", muscle: "chest", type: "compound", equipment: ["home_full_equipment", "gym"], difficulty: "intermediate", joints: ["shoulder"], icon: "Dumbbell", description: "استلقِ على مقعد مسطح مع دمبل بكل يد عند الصدر، وادفعهما لأعلى حتى استقامة الذراعين ثم أنزلهما ببطء.", descriptionEn: "Lie on a flat bench with a dumbbell in each hand at chest level, push them up until arms are straight, then lower slowly." },
  { id: "barbell_bench", name: "ضغط البنش بالبار", nameEn: "Barbell bench press", muscle: "chest", type: "compound", equipment: ["gym"], difficulty: "intermediate", joints: ["shoulder", "wrist"], icon: "Dumbbell", description: "استلقِ على مقعد البنش وأنزل البار حتى يلامس الصدر بلطف، ثم ادفعه لأعلى حتى استقامة الذراعين.", descriptionEn: "Lie on a bench press and lower the bar until it gently touches your chest, then push it back up until your arms are straight." },
  { id: "incline_barbell_bench", name: "ضغط بنش مائل بالبار", nameEn: "Incline barbell bench press", muscle: "chest", type: "compound", equipment: ["gym"], difficulty: "advanced", joints: ["shoulder", "wrist"], icon: "Dumbbell", description: "على مقعد مائل، أنزل البار نحو الصدر العلوي ثم ادفعه لأعلى لاستهداف الصدر العلوي.", descriptionEn: "On an incline bench, lower the bar toward your upper chest then press it up to emphasize the upper chest." },
  { id: "cable_chest_press", name: "ضغط الصدر بالكابل", nameEn: "Cable chest press", muscle: "chest", type: "compound", equipment: ["gym"], difficulty: "intermediate", joints: ["shoulder"], icon: "Dumbbell", description: "قف بين جهاز الكابل وادفع المقبضين للأمام حتى استقامة الذراعين مع ثبات الجذع.", descriptionEn: "Stand between the cable machine and push the handles forward until your arms are straight while keeping your torso stable." },
  { id: "cable_fly", name: "تفتيح الصدر بالكابل", nameEn: "Cable chest fly", muscle: "chest", type: "isolation", equipment: ["gym"], difficulty: "intermediate", joints: ["shoulder"], icon: "Dumbbell", description: "قف بين جهازي كابل وحرّك يديك من الجانبين إلى الأمام في قوس واسع مع ثني بسيط بالمرفقين.", descriptionEn: "Stand between two cable stations and bring your hands from the sides to the front in a wide arc with a slight elbow bend." },
  { id: "db_fly", name: "تفتيح الصدر بالدمبل", nameEn: "Dumbbell chest fly", muscle: "chest", type: "isolation", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "intermediate", joints: ["shoulder"], icon: "Dumbbell", description: "استلقِ مع دمبل بكل يد فوق الصدر، وافتح ذراعيك للجانبين بقوس واسع ثم أعدهما.", descriptionEn: "Lie down with a dumbbell in each hand above your chest, open your arms out to the sides in a wide arc, then bring them back." },
  { id: "chair_dips", name: "غطس الترايسبس على كرسي", nameEn: "Chair tricep dips", muscle: "chest", type: "compound", equipment: ["home_no_equipment", "home_light_weights"], difficulty: "beginner", joints: ["shoulder", "elbow"], icon: "Dumbbell", description: "استند بيديك على حافة كرسي ثابت وقدميك للأمام، وانزل بجسمك عمودياً ثم ادفع لأعلى.", descriptionEn: "Support yourself with your hands on the edge of a stable chair with your feet forward, lower your body, then push back up." },

  // ===================== ظهر (back) =====================
  { id: "superman", name: "السوبرمان", nameEn: "Superman", muscle: "back", type: "isolation", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: [], icon: "PersonStanding", description: "استلقِ على بطنك وارفع الذراعين والساقين معاً عن الأرض في آن واحد، ثم اخفضهما ببطء.", descriptionEn: "Lie face down and lift both your arms and legs off the ground at the same time, then lower them slowly." },
  { id: "reverse_snow_angel", name: "ملاك الثلج المعكوس", nameEn: "Reverse snow angel", muscle: "back", type: "isolation", equipment: ["home_no_equipment", "home_light_weights"], difficulty: "beginner", joints: ["shoulder"], icon: "PersonStanding", description: "استلقِ على بطنك وحرّك ذراعيك من جانبيك إلى أعلى الرأس وبالعكس مع رفعهما قليلاً عن الأرض.", descriptionEn: "Lie face down and move your arms from your sides up above your head and back, lifting them slightly off the ground." },
  { id: "bird_dog", name: "الكلب الطائر", nameEn: "Bird dog", muscle: "back", type: "isolation", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: ["lower_back"], icon: "PersonStanding", description: "على وضعية الزحف، مدّ ذراعاً وساقاً معاكسة في آن واحد مع ثبات الجذع، ثم بدّل الجانب.", descriptionEn: "On all fours, extend one arm and the opposite leg at the same time while keeping your torso steady, then switch sides." },
  { id: "db_bent_row", name: "صف منحني بالدمبل", nameEn: "Dumbbell bent-over row", muscle: "back", type: "compound", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "beginner", joints: ["lower_back"], icon: "Dumbbell", description: "انحنِ للأمام قليلاً مع استقامة الظهر، واسحب الدمبلين نحو خصرك ثم أنزلهما ببطء.", descriptionEn: "Bend forward slightly while keeping your back straight, pull the dumbbells toward your waist, then lower them slowly." },
  { id: "db_single_row", name: "صف بدمبل واحد", nameEn: "Single-arm dumbbell row", muscle: "back", type: "compound", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "beginner", joints: [], icon: "Dumbbell", description: "استند بيد وركبة على مقعد، واسحب الدمبل باليد الأخرى نحو الخصر مع ثبات الجذع.", descriptionEn: "Support yourself with one hand and one knee on a bench, and pull the dumbbell with your other hand toward your waist." },
  { id: "pullup", name: "العقلة", nameEn: "Pull-up", muscle: "back", type: "compound", equipment: ["gym", "home_full_equipment"], difficulty: "advanced", joints: ["shoulder"], icon: "Dumbbell", description: "تعلّق من القضيب بقبضة عريضة واسحب جسمك لأعلى حتى يقترب ذقنك من القضيب.", descriptionEn: "Hang from the bar with a wide grip and pull your body up until your chin nears the bar." },
  { id: "assisted_pullup", name: "عقلة بمساعدة", nameEn: "Assisted / band-assisted pull-up", muscle: "back", type: "compound", equipment: ["gym"], difficulty: "intermediate", joints: ["shoulder"], icon: "Dumbbell", description: "استخدم جهاز المساعدة أو حزام مطاطي لتخفيف الوزن أثناء أداء العقلة حتى تُبنى القوة الكافية.", descriptionEn: "Use an assisted pull-up machine or resistance band to reduce the load while performing the movement until enough strength is built." },
  { id: "lat_pulldown", name: "سحب أمامي (Lat Pulldown)", nameEn: "Lat pulldown", muscle: "back", type: "compound", equipment: ["gym"], difficulty: "beginner", joints: ["shoulder"], icon: "Dumbbell", description: "اجلس أمام جهاز السحب واسحب القضيب نحو أعلى الصدر مع ثبات الجذع، ثم أعده ببطء.", descriptionEn: "Sit in front of the pulldown machine and pull the bar toward the top of your chest while keeping your torso stable, then return it slowly." },
  { id: "seated_cable_row", name: "صف الكابل الجالس", nameEn: "Seated cable row", muscle: "back", type: "compound", equipment: ["gym"], difficulty: "beginner", joints: ["lower_back"], icon: "Dumbbell", description: "اجلس أمام جهاز الكابل واسحب المقبض نحو بطنك مع تقريب لوحي الكتف، ثم أعده ببطء.", descriptionEn: "Sit in front of the cable machine and pull the handle toward your stomach while squeezing your shoulder blades together." },
  { id: "barbell_row", name: "صف منحني بالبار", nameEn: "Barbell bent-over row", muscle: "back", type: "compound", equipment: ["gym"], difficulty: "advanced", joints: ["lower_back"], icon: "Dumbbell", description: "انحنِ للأمام مع استقامة الظهر تماماً واسحب البار نحو أسفل الصدر، ثم أنزله ببطء.", descriptionEn: "Bend forward keeping your back completely straight and pull the bar toward your lower chest, then lower it slowly." },
  { id: "back_extension", name: "امتداد أسفل الظهر", nameEn: "Back extension", muscle: "back", type: "isolation", equipment: ["gym"], difficulty: "intermediate", joints: ["lower_back"], icon: "Dumbbell", description: "على جهاز امتداد الظهر، انزل بجذعك للأمام ثم ارفعه حتى استقامة الجسم مع الحفاظ على تحكّم كامل.", descriptionEn: "On a back extension bench, lower your torso forward then raise it until your body is straight, keeping full control." },

  // ===================== أكتاف (shoulders) =====================
  { id: "pike_pushup", name: "ضغط الكتف (الحمامة)", nameEn: "Pike push-up", muscle: "shoulders", type: "compound", equipment: ["gym", "home_full_equipment", "home_no_equipment"], difficulty: "intermediate", joints: ["shoulder", "wrist"], icon: "Dumbbell", description: "ارفع الوركين لأعلى فتصبح بوضعية V مقلوبة، وانزل برأسك نحو الأرض بين يديك مع ثني المرفقين.", descriptionEn: "Raise your hips up into an inverted V position, and lower your head toward the ground between your hands." },
  { id: "db_shoulder_press", name: "ضغط الكتف بالدمبل", nameEn: "Dumbbell shoulder press", muscle: "shoulders", type: "compound", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "beginner", joints: ["shoulder"], icon: "Dumbbell", description: "امسك دمبلين عند مستوى الكتفين، وادفعهما لأعلى حتى استقامة الذراعين ثم أعدهما ببطء.", descriptionEn: "Hold a dumbbell in each hand at shoulder height, push them up until your arms are straight, then lower them back slowly." },
  { id: "barbell_ohp", name: "ضغط عسكري بالبار", nameEn: "Barbell overhead press", muscle: "shoulders", type: "compound", equipment: ["gym"], difficulty: "advanced", joints: ["shoulder", "lower_back"], icon: "Dumbbell", description: "امسك البار عند الكتفين وادفعه فوق الرأس حتى استقامة الذراعين مع ثبات الجذع.", descriptionEn: "Hold the bar at shoulder height and press it overhead until your arms are straight while keeping your core tight." },
  { id: "lateral_raise", name: "رفرفة جانبية بالدمبل", nameEn: "Dumbbell lateral raise", muscle: "shoulders", type: "isolation", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "beginner", joints: ["shoulder"], icon: "Dumbbell", description: "امسك دمبلين جانب جسمك وارفعهما للجانبين حتى مستوى الكتفين، ثم أنزلهما ببطء.", descriptionEn: "Hold a dumbbell at each side and raise them out to the sides up to shoulder height, then lower slowly." },
  { id: "front_raise", name: "رفرفة أمامية بالدمبل", nameEn: "Dumbbell front raise", muscle: "shoulders", type: "isolation", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "beginner", joints: ["shoulder"], icon: "Dumbbell", description: "امسك دمبلين أمام فخذيك وارفعهما للأمام حتى مستوى الكتفين، ثم أنزلهما ببطء.", descriptionEn: "Hold a dumbbell in front of each thigh and raise them forward to shoulder height, then lower slowly." },
  { id: "cable_lateral_raise", name: "رفرفة جانبية بالكابل", nameEn: "Cable lateral raise", muscle: "shoulders", type: "isolation", equipment: ["gym"], difficulty: "intermediate", joints: ["shoulder"], icon: "Dumbbell", description: "قف بجانب جهاز الكابل واسحب المقبض للجانب حتى مستوى الكتف مع تحكّم كامل بالنزول.", descriptionEn: "Stand beside the cable machine and pull the handle out to the side up to shoulder height with full control on the way down." },
  { id: "arm_circles", name: "دوائر الذراعين", nameEn: "Arm circles", muscle: "shoulders", type: "isolation", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: [], icon: "Wind", description: "مدّ ذراعيك أفقياً وارسم دوائر صغيرة ثم كبيرة تدريجياً لتنشيط مفصل الكتف.", descriptionEn: "Extend your arms horizontally and draw small then gradually larger circles to activate the shoulder joint." },
  { id: "rear_delt_fly", name: "رفرفة الكتف الخلفي", nameEn: "Rear delt fly", muscle: "shoulders", type: "isolation", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "intermediate", joints: ["shoulder"], icon: "Dumbbell", description: "انحنِ للأمام مع دمبل بكل يد، وافتح ذراعيك للجانبين مع تقريب لوحي الكتف.", descriptionEn: "Bend forward with a dumbbell in each hand, and open your arms out to the sides while squeezing your shoulder blades." },

  // ===================== باي (biceps) =====================
  { id: "db_bicep_curl", name: "تمرين الباي بالدمبل", nameEn: "Dumbbell bicep curl", muscle: "biceps", type: "isolation", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "beginner", joints: ["elbow"], icon: "Dumbbell", description: "امسك دمبلاً بكل يد جانب جسمك، واثنِ المرفقين لرفعهما نحو الكتفين ثم أنزلهما ببطء.", descriptionEn: "Hold a dumbbell at each side, bend your elbows to curl them toward your shoulders, then lower slowly." },
  { id: "hammer_curl", name: "تمرين الباي (قبضة مطرقة)", nameEn: "Hammer curl", muscle: "biceps", type: "isolation", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "beginner", joints: ["elbow"], icon: "Dumbbell", description: "امسك الدمبلين بقبضة عمودية (كالمطرقة) وارفعهما نحو الكتفين مع ثبات المرفقين.", descriptionEn: "Hold the dumbbells with a vertical (hammer) grip and curl them toward your shoulders while keeping your elbows steady." },
  { id: "barbell_curl", name: "تمرين الباي بالبار", nameEn: "Barbell curl", muscle: "biceps", type: "isolation", equipment: ["gym"], difficulty: "intermediate", joints: ["elbow", "wrist"], icon: "Dumbbell", description: "امسك البار بقبضة عرضية وارفعه نحو الصدر بثني المرفقين، ثم أنزله ببطء.", descriptionEn: "Hold the bar with an underhand grip and curl it toward your chest by bending your elbows, then lower slowly." },
  { id: "cable_curl", name: "تمرين الباي بالكابل", nameEn: "Cable bicep curl", muscle: "biceps", type: "isolation", equipment: ["gym"], difficulty: "beginner", joints: ["elbow"], icon: "Dumbbell", description: "قف أمام جهاز الكابل السفلي واسحب المقبض نحو الكتفين بثني المرفقين فقط.", descriptionEn: "Stand in front of the low cable pulley and curl the handle toward your shoulders using only your elbows." },
  { id: "resistance_band_curl", name: "تمرين الباي بحزام مطاطي", nameEn: "Resistance band curl", muscle: "biceps", type: "isolation", equipment: ["home_no_equipment", "home_light_weights"], difficulty: "beginner", joints: ["elbow"], icon: "Dumbbell", description: "قف على حزام مطاطي وامسك طرفيه، وارفعهما نحو الكتفين بثني المرفقين.", descriptionEn: "Stand on a resistance band holding both ends, and curl them toward your shoulders by bending your elbows." },

  // ===================== ترايسبس (triceps) =====================
  { id: "diamond_pushup", name: "ضغط الماس", nameEn: "Diamond push-up", muscle: "triceps", type: "compound", equipment: ["gym", "home_full_equipment", "home_no_equipment"], difficulty: "intermediate", joints: ["wrist", "elbow"], icon: "Dumbbell", description: "قرِّب يديك تحت الصدر لتشكيل شكل الماس بالأصابع، وأدِّ الضغط ليركّز الحمل على الترايسبس.", descriptionEn: "Bring your hands together under your chest to form a diamond shape with your fingers, and perform the push-up to focus the load on your triceps." },
  { id: "parallel_dips", name: "غطس المتوازي", nameEn: "Parallel bar dips", muscle: "triceps", type: "compound", equipment: ["gym", "home_full_equipment"], difficulty: "advanced", joints: ["shoulder", "elbow"], icon: "Dumbbell", description: "استند على قضيبي المتوازي وانزل بجسمك حتى زاوية مريحة بالمرفقين، ثم ادفع لأعلى.", descriptionEn: "Support yourself on parallel bars and lower your body until your elbows reach a comfortable angle, then push back up." },
  { id: "db_overhead_extension", name: "مد الترايسبس فوق الرأس", nameEn: "Overhead dumbbell triceps extension", muscle: "triceps", type: "isolation", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "beginner", joints: ["elbow", "shoulder"], icon: "Dumbbell", description: "امسك دمبلاً بيدين فوق الرأس، وأنزله خلف الرأس بثني المرفقين ثم ادفعه لأعلى.", descriptionEn: "Hold a dumbbell with both hands overhead, lower it behind your head by bending your elbows, then press it back up." },
  { id: "db_kickback", name: "ركلة الترايسبس الخلفية", nameEn: "Dumbbell triceps kickback", muscle: "triceps", type: "isolation", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "beginner", joints: ["elbow"], icon: "Dumbbell", description: "انحنِ للأمام مع دمبل بيد، وادفعه للخلف بتمديد المرفق حتى استقامة الذراع.", descriptionEn: "Bend forward with a dumbbell in one hand, and push it backward by extending your elbow until your arm is straight." },
  { id: "cable_pushdown", name: "دفع الترايسبس بالكابل", nameEn: "Cable triceps pushdown", muscle: "triceps", type: "isolation", equipment: ["gym"], difficulty: "beginner", joints: ["elbow"], icon: "Dumbbell", description: "قف أمام جهاز الكابل العلوي وادفع المقبض للأسفل بتمديد المرفقين مع ثبات الكتفين.", descriptionEn: "Stand in front of the high cable pulley and push the handle down by extending your elbows while keeping your shoulders steady." },
  { id: "close_grip_bench", name: "ضغط بنش بقبضة ضيقة", nameEn: "Close-grip bench press", muscle: "triceps", type: "compound", equipment: ["gym"], difficulty: "advanced", joints: ["wrist", "elbow"], icon: "Dumbbell", description: "استلقِ على البنش وامسك البار بقبضة ضيقة بعرض الكتفين، وادفعه لأعلى مع تركيز الحمل على الترايسبس.", descriptionEn: "Lie on the bench and hold the bar with a shoulder-width grip, pressing it up with the load focused on the triceps." },

  // ===================== أرجل - كوادس (quads) =====================
  { id: "squat", name: "سكوات (القرفصاء)", nameEn: "Bodyweight squat", muscle: "quads", type: "compound", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: ["knee"], icon: "Footprints", description: "قف بعرض الكتفين وانزل بالوركين للخلف وللأسفل كأنك تجلس على كرسي، ثم عد للوقوف.", descriptionEn: "Stand shoulder-width apart and lower your hips back and down as if sitting in a chair, then return to standing." },
  { id: "lunge", name: "اندفاع الرجل (لانج)", nameEn: "Lunge", muscle: "quads", type: "compound", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: ["knee"], icon: "Footprints", description: "خطِ خطوة للأمام وانزل حتى تصل الركبة الخلفية قريباً من الأرض، ثم عد للوقوف وبدّل الرجل.", descriptionEn: "Step forward and lower yourself until your back knee nearly touches the ground, then return to standing and switch legs." },
  { id: "wall_sit", name: "جلسة الحائط", nameEn: "Wall sit", muscle: "quads", type: "isolation", equipment: ["home_no_equipment", "home_light_weights"], difficulty: "beginner", joints: ["knee"], icon: "Footprints", description: "استند بظهرك على حائط وانزل حتى تصبح زاوية الركبتين 90 درجة، وحافظ على الوضعية.", descriptionEn: "Lean your back against a wall and lower down until your knees form a 90-degree angle, and hold the position." },
  { id: "step_up", name: "الصعود على مرتفع", nameEn: "Step-up", muscle: "quads", type: "compound", equipment: ["home_no_equipment", "home_light_weights", "home_full_equipment"], difficulty: "beginner", joints: ["knee"], icon: "Footprints", description: "اصعد بقدم واحدة على كرسي أو درجة ثابتة، ثم انزل ببطء وكرّر بالرجل الأخرى.", descriptionEn: "Step up onto a chair or sturdy step with one foot, then step down slowly and repeat with the other leg." },
  { id: "db_goblet_squat", name: "سكوات الكأس بالدمبل", nameEn: "Dumbbell goblet squat", muscle: "quads", type: "compound", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "beginner", joints: ["knee"], icon: "Dumbbell", description: "امسك دمبلاً عمودياً أمام صدرك وأدِّ حركة السكوات مع الحفاظ على استقامة الظهر.", descriptionEn: "Hold a dumbbell vertically in front of your chest and perform a squat while keeping your back straight." },
  { id: "leg_press", name: "مكبس الأرجل", nameEn: "Leg press machine", muscle: "quads", type: "compound", equipment: ["gym"], difficulty: "intermediate", joints: ["knee"], icon: "Dumbbell", description: "اجلس على جهاز مكبس الأرجل وادفع اللوح بقدميك حتى استقامة الركبتين تقريباً، ثم أعده ببطء.", descriptionEn: "Sit on the leg press machine and push the platform with your feet until your knees are nearly straight, then return it slowly." },
  { id: "barbell_squat", name: "سكوات بالبار", nameEn: "Barbell back squat", muscle: "quads", type: "compound", equipment: ["gym"], difficulty: "advanced", joints: ["knee", "lower_back"], icon: "Dumbbell", description: "ضع البار على أعلى الظهر وانزل بالوركين للخلف وللأسفل حتى توازي الفخذين الأرض، ثم عد للوقوف.", descriptionEn: "Place the bar on your upper back and lower your hips back and down until your thighs are parallel to the ground." },
  { id: "leg_extension", name: "مد الرجل (Leg Extension)", nameEn: "Leg extension machine", muscle: "quads", type: "isolation", equipment: ["gym"], difficulty: "beginner", joints: ["knee"], icon: "Dumbbell", description: "اجلس على الجهاز وادفع اللوح بمدّ الركبتين حتى استقامة الرجلين، ثم أنزله ببطء.", descriptionEn: "Sit on the machine and push the pad by extending your knees until your legs are straight, then lower it slowly." },

  // ===================== أرجل - هامسترنغ (hamstrings) =====================
  { id: "glute_ham_raise_beginner", name: "رفعة الأرداف مع مد الرجل", nameEn: "Standing leg curl (band)", muscle: "hamstrings", type: "isolation", equipment: ["home_no_equipment", "home_light_weights"], difficulty: "beginner", joints: ["knee"], icon: "Footprints", description: "قف واثنِ ركبة واحدة للخلف رافعاً الكعب نحو المؤخرة مع ثبات الفخذ، ثم أنزلها وبدّل.", descriptionEn: "Stand and bend one knee back, raising the heel toward your glutes while keeping the thigh still, then switch." },
  { id: "db_rdl", name: "رفعة رومانية بالدمبل", nameEn: "Dumbbell Romanian deadlift", muscle: "hamstrings", type: "compound", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "intermediate", joints: ["lower_back"], icon: "Dumbbell", description: "امسك دمبلين أمام فخذيك وانحنِ للأمام من الوركين مع استقامة الظهر حتى تشعر بشد الفخذ الخلفي.", descriptionEn: "Hold a dumbbell in each hand in front of your thighs and hinge forward at the hips while keeping your back straight." },
  { id: "leg_curl", name: "ثني الرجل (Leg Curl)", nameEn: "Leg curl machine", muscle: "hamstrings", type: "isolation", equipment: ["gym"], difficulty: "beginner", joints: ["knee"], icon: "Dumbbell", description: "استلقِ على جهاز ثني الرجل واسحب الوسادة نحو المؤخرة بثني الركبتين، ثم أعدها ببطء.", descriptionEn: "Lie on the leg curl machine and pull the pad toward your glutes by bending your knees, then return it slowly." },
  { id: "barbell_rdl", name: "رفعة رومانية بالبار", nameEn: "Barbell Romanian deadlift", muscle: "hamstrings", type: "compound", equipment: ["gym"], difficulty: "advanced", joints: ["lower_back"], icon: "Dumbbell", description: "امسك البار أمام فخذيك وانحنِ من الوركين مع استقامة الظهر التامة حتى تشعر بشد خلف الفخذ.", descriptionEn: "Hold the bar in front of your thighs and hinge from the hips keeping your back completely straight until you feel a hamstring stretch." },
  { id: "single_leg_rdl", name: "رفعة رومانية على رجل واحدة", nameEn: "Single-leg RDL (bodyweight)", muscle: "hamstrings", type: "compound", equipment: ["home_no_equipment", "home_light_weights"], difficulty: "beginner", joints: ["lower_back"], icon: "Footprints", description: "قف على رجل واحدة وانحنِ للأمام مادّاً الرجل الأخرى للخلف مع استقامة الظهر، ثم عد للوقوف.", descriptionEn: "Stand on one leg and hinge forward while extending the other leg back, keeping your back straight, then return to standing." },
  { id: "good_morning", name: "تمرين الصباح الطيب", nameEn: "Good morning (bodyweight)", muscle: "hamstrings", type: "isolation", equipment: ["home_no_equipment", "home_light_weights"], difficulty: "beginner", joints: ["lower_back"], icon: "PersonStanding", description: "ضع يديك خلف رأسك وانحنِ من الوركين للأمام مع استقامة الظهر، ثم عد للوقوف ببطء.", descriptionEn: "Place your hands behind your head and hinge forward from the hips keeping your back straight, then return to standing slowly." },

  // ===================== أرداف (glutes) =====================
  { id: "glute_bridge", name: "جسر الأرداف", nameEn: "Glute bridge", muscle: "glutes", type: "isolation", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: [], icon: "PersonStanding", description: "استلقِ على ظهرك مع ثني الركبتين، وارفع الوركين لأعلى بالضغط على الكعبين، ثم أنزلهما ببطء.", descriptionEn: "Lie on your back with your knees bent, raise your hips up by pressing through your heels, then lower them slowly." },
  { id: "hip_thrust", name: "دفع الورك (Hip Thrust)", nameEn: "Hip thrust", muscle: "glutes", type: "compound", equipment: ["home_full_equipment", "gym"], difficulty: "intermediate", joints: ["hip"], icon: "PersonStanding", description: "استند بأعلى ظهرك على مقعد مع البار فوق الوركين، وادفع الوركين لأعلى حتى استقامة الجسم.", descriptionEn: "Rest your upper back on a bench with a bar over your hips, and thrust your hips up until your body is straight." },
  { id: "single_leg_glute_bridge", name: "جسر الأرداف على رجل واحدة", nameEn: "Single-leg glute bridge", muscle: "glutes", type: "isolation", equipment: ["home_no_equipment", "home_light_weights"], difficulty: "beginner", joints: [], icon: "PersonStanding", description: "استلقِ على ظهرك مع مدّ رجل واحدة، وارفع الوركين بالضغط على كعب الرجل الأخرى.", descriptionEn: "Lie on your back with one leg extended, and raise your hips by pressing through the heel of the other leg." },
  { id: "cable_kickback", name: "ركلة الأرداف بالكابل", nameEn: "Cable glute kickback", muscle: "glutes", type: "isolation", equipment: ["gym"], difficulty: "intermediate", joints: ["hip"], icon: "Dumbbell", description: "ثبّت الكابل بكاحلك وادفع رجلك للخلف والأعلى مع ثبات الجذع، ثم أعدها ببطء.", descriptionEn: "Attach the cable to your ankle and push your leg back and up while keeping your torso stable, then return it slowly." },
  { id: "bulgarian_split_squat", name: "سكوات بلغاري", nameEn: "Bulgarian split squat", muscle: "glutes", type: "compound", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "advanced", joints: ["knee"], icon: "Footprints", description: "ضع رجلك الخلفية على مقعد مرتفع خلفك وانزل بالرجل الأمامية حتى زاوية 90 درجة، ثم عد للوقوف.", descriptionEn: "Place your back foot on a raised bench behind you and lower your front leg to a 90-degree angle, then return to standing." },

  // ===================== سمانة (calves) =====================
  { id: "calf_raise", name: "رفعة السمانة", nameEn: "Calf raise", muscle: "calves", type: "isolation", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: [], icon: "Footprints", description: "قف باستقامة وارتفع على أطراف أصابع قدميك ببطء، ثم انزل ببطء أكبر.", descriptionEn: "Stand straight and rise up onto your toes slowly, then lower down even more slowly." },
  { id: "seated_calf_raise", name: "رفعة السمانة جالساً", nameEn: "Seated calf raise", muscle: "calves", type: "isolation", equipment: ["gym"], difficulty: "beginner", joints: [], icon: "Footprints", description: "اجلس على الجهاز مع الوزن فوق الركبتين، وارتفع على أطراف الأصابع ثم أنزل ببطء.", descriptionEn: "Sit on the machine with the weight over your knees, rise onto your toes, then lower slowly." },
  { id: "single_leg_calf_raise", name: "رفعة السمانة على رجل واحدة", nameEn: "Single-leg calf raise", muscle: "calves", type: "isolation", equipment: ["home_no_equipment", "home_light_weights"], difficulty: "intermediate", joints: [], icon: "Footprints", description: "قف على رجل واحدة وارتفع على طرف أصابعها ببطء، ثم انزل وكرّر بالرجل الأخرى.", descriptionEn: "Stand on one leg and rise onto its toes slowly, then lower and repeat with the other leg." },

  // ===================== بطن / الجذع (abs) =====================
  { id: "plank", name: "البلانك", nameEn: "Plank", muscle: "abs", type: "isolation", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: ["wrist", "lower_back"], icon: "PersonStanding", description: "استند على ساعديك وأطراف أصابع قدميك مع استقامة الجسم بالكامل، وحافظ على الوضعية.", descriptionEn: "Support yourself on your forearms and toes keeping your body in a straight line, and hold the position." },
  { id: "plank_shoulder_tap", name: "لمس الكتف بوضعية البلانك", nameEn: "Plank shoulder tap", muscle: "abs", type: "isolation", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "intermediate", joints: ["wrist"], icon: "PersonStanding", description: "في وضعية البلانك، المس كتفك المعاكس بيدك بالتناوب مع ثبات الوركين قدر الإمكان.", descriptionEn: "In a plank position, touch your opposite shoulder with alternating hands while keeping your hips as steady as possible." },
  { id: "crunch", name: "تمرين البطن (Crunch)", nameEn: "Crunch", muscle: "abs", type: "isolation", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: ["neck"], icon: "PersonStanding", description: "استلقِ مع ثني الركبتين وارفع أعلى الجذع قليلاً عن الأرض بشدّ البطن، ثم أنزله ببطء.", descriptionEn: "Lie down with knees bent and lift your upper torso slightly off the ground by contracting your abs, then lower slowly." },
  { id: "leg_raise", name: "رفع الأرجل", nameEn: "Lying leg raise", muscle: "abs", type: "isolation", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "intermediate", joints: ["lower_back"], icon: "PersonStanding", description: "استلقِ على ظهرك وارفع رجليك المستقيمتين حتى الزاوية القائمة، ثم أنزلهما ببطء دون لمس الأرض.", descriptionEn: "Lie on your back and raise your straight legs to a right angle, then lower them slowly without touching the ground." },
  { id: "russian_twist", name: "لفّة روسية", nameEn: "Russian twist", muscle: "abs", type: "isolation", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "intermediate", joints: ["lower_back"], icon: "PersonStanding", description: "اجلس مع رفع القدمين قليلاً عن الأرض، ولفّ جذعك من جانب لآخر مع لمس الأرض بيديك.", descriptionEn: "Sit with your feet slightly raised off the ground, and twist your torso from side to side touching the ground with your hands." },
  { id: "hanging_knee_raise", name: "رفع الركبتين معلَّقاً", nameEn: "Hanging knee raise", muscle: "abs", type: "isolation", equipment: ["gym", "home_full_equipment"], difficulty: "advanced", joints: ["shoulder"], icon: "PersonStanding", description: "تعلّق من القضيب وارفع ركبتيك نحو الصدر مع تحكّم كامل بلا تأرجح، ثم أنزلهما ببطء.", descriptionEn: "Hang from the bar and raise your knees toward your chest with full control and no swinging, then lower slowly." },
  { id: "cable_crunch", name: "كرانش الكابل", nameEn: "Cable crunch", muscle: "abs", type: "isolation", equipment: ["gym"], difficulty: "intermediate", joints: ["lower_back"], icon: "Dumbbell", description: "اركع أمام جهاز الكابل العلوي وانحنِ بجذعك للأسفل بشدّ البطن مع ثبات الوركين.", descriptionEn: "Kneel in front of the high cable and curl your torso down by contracting your abs while keeping your hips still." },
  { id: "side_plank", name: "البلانك الجانبي", nameEn: "Side plank", muscle: "abs", type: "isolation", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "intermediate", joints: ["shoulder", "wrist"], icon: "PersonStanding", description: "استند على ساعد واحد وجانب قدم واحدة مع استقامة الجسم أفقياً، وحافظ على الوضعية ثم بدّل الجانب.", descriptionEn: "Support yourself on one forearm and the side of one foot keeping your body straight horizontally, hold, then switch sides." },

  // ===================== كامل الجسم (full_body) =====================
  { id: "burpee", name: "بيربي", nameEn: "Burpee", muscle: "full_body", type: "compound", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "intermediate", joints: ["knee", "wrist"], icon: "Flame", description: "انزل لوضعية الضغط ثم اقفز بقدميك للأمام وقف مع قفزة عمودية، وكرّر بإيقاع مستمر.", descriptionEn: "Drop into a push-up position, then jump your feet forward and stand up with a vertical jump, repeating at a steady rhythm." },
  { id: "mountain_climber", name: "متسلق الجبل", nameEn: "Mountain climber", muscle: "full_body", type: "compound", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: ["wrist"], icon: "Flame", description: "من وضعية الضغط، اسحب ركبتيك بالتناوب نحو الصدر بسرعة مع ثبات الجذع.", descriptionEn: "From a push-up position, quickly alternate pulling your knees toward your chest while keeping your torso stable." },
  { id: "bear_crawl", name: "زحف الدب", nameEn: "Bear crawl", muscle: "full_body", type: "compound", equipment: ["home_no_equipment", "home_light_weights"], difficulty: "intermediate", joints: ["wrist"], icon: "PersonStanding", description: "تحرّك للأمام والخلف على يديك وقدميك مع رفع الركبتين قليلاً عن الأرض، وحافظ على استقامة الظهر.", descriptionEn: "Move forward and backward on your hands and feet with your knees slightly raised off the ground, keeping your back straight." },
  { id: "db_thruster", name: "ثرَستر بالدمبل", nameEn: "Dumbbell thruster", muscle: "full_body", type: "compound", equipment: ["home_light_weights", "home_full_equipment", "gym"], difficulty: "intermediate", joints: ["knee", "shoulder"], icon: "Dumbbell", description: "امسك دمبلين عند الكتفين، انزل لسكوات ثم انفجر للوقوف مع دفع الدمبلين فوق الرأس.", descriptionEn: "Hold a dumbbell in each hand at shoulder height, drop into a squat, then explode up to standing while pushing the dumbbells overhead." },
  { id: "kettlebell_swing", name: "أرجحة الكيتل بيل", nameEn: "Kettlebell swing", muscle: "full_body", type: "compound", equipment: ["home_full_equipment", "gym"], difficulty: "intermediate", joints: ["lower_back"], icon: "Dumbbell", description: "أمسك الكيتل بيل بيدين وأرجحه من بين الساقين إلى مستوى الصدر بدفع قوي من الوركين.", descriptionEn: "Hold the kettlebell with both hands and swing it from between your legs up to chest height with a powerful hip drive." },
  { id: "rowing_sprint", name: "سبرنت جهاز التجديف", nameEn: "Rowing machine sprint", muscle: "full_body", type: "compound", equipment: ["gym"], difficulty: "advanced", joints: ["lower_back"], icon: "Dumbbell", description: "جدّف بأقصى جهد لمدة 30 ثانية، ثم استرح 30 ثانية، وكرّر.", descriptionEn: "Row at maximum effort for 30 seconds, then rest for 30 seconds, and repeat." },

  // ===================== كارديو (cardio) =====================
  { id: "jumping_jack", name: "نطة الفتح", nameEn: "Jumping jacks", muscle: "cardio", type: "cardio", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: ["knee"], icon: "HeartPulse", description: "اقفز مع فتح الساقين والذراعين للأعلى في آن واحد، ثم عد للوضعية الأصلية بسرعة.", descriptionEn: "Jump while opening your legs and raising your arms up at the same time, then quickly return to the starting position." },
  { id: "high_knees", name: "رفع الركبتين", nameEn: "High knees", muscle: "cardio", type: "cardio", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: ["knee"], icon: "HeartPulse", description: "اركض في مكانك مع رفع الركبتين لأعلى قدر الإمكان بسرعة.", descriptionEn: "Run in place while raising your knees as high as possible, as fast as you can." },
  { id: "butt_kicks", name: "ركل المؤخرة", nameEn: "Butt kicks", muscle: "cardio", type: "cardio", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: [], icon: "HeartPulse", description: "اركض في مكانك مع محاولة لمس كعبيك لمؤخرتك بسرعة.", descriptionEn: "Run in place while trying to touch your glutes with your heels, quickly." },
  { id: "star_jump", name: "قفزة النجمة", nameEn: "Star jump", muscle: "cardio", type: "cardio", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: ["knee"], icon: "HeartPulse", description: "اقفز من وضعية القرفصاء مع فرد الذراعين والساقين على شكل نجمة في الهواء.", descriptionEn: "Jump up from a squat position while spreading your arms and legs into a star shape in the air." },
  { id: "shadow_jump_rope", name: "قفز الحبل (بلا حبل)", nameEn: "Shadow jump rope", muscle: "cardio", type: "cardio", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: ["knee"], icon: "HeartPulse", description: "قلّد حركة القفز على الحبل بالوثب الخفيف مع تحريك المعصمين، حتى دون حبل فعلي.", descriptionEn: "Mimic a jump rope motion with light hops and wrist movements, even without an actual rope." },
  { id: "jump_rope", name: "نط الحبل", nameEn: "Jump rope", muscle: "cardio", type: "cardio", equipment: ["home_no_equipment", "home_light_weights", "home_full_equipment", "gym"], difficulty: "intermediate", joints: ["knee"], icon: "HeartPulse", description: "انطّ بحبل حقيقي بإيقاع ثابت مع الحفاظ على استقامة الجسم.", descriptionEn: "Jump rope at a steady rhythm while keeping your body upright." },
  { id: "treadmill_run", name: "الجري على المشاية", nameEn: "Treadmill running", muscle: "cardio", type: "cardio", equipment: ["gym"], difficulty: "beginner", joints: ["knee"], icon: "Bike", description: "اجرِ أو امشِ بسرعة ثابتة على المشاية مع رفع السرعة تدريجياً حسب لياقتك.", descriptionEn: "Run or walk at a steady pace on the treadmill, gradually increasing speed according to your fitness level." },
  { id: "stationary_bike", name: "الدراجة الثابتة", nameEn: "Stationary bike", muscle: "cardio", type: "cardio", equipment: ["gym", "home_full_equipment"], difficulty: "beginner", joints: ["knee"], icon: "Bike", description: "اضبط مقاومة متوسطة وادفع بانتظام لمدة الجلسة مع الحفاظ على معدل نبض ثابت.", descriptionEn: "Set a moderate resistance and pedal steadily for the session while keeping a consistent heart rate." },
  { id: "elliptical", name: "جهاز الإليبتيكال", nameEn: "Elliptical machine", muscle: "cardio", type: "cardio", equipment: ["gym"], difficulty: "beginner", joints: [], icon: "Bike", description: "حرّك الجهاز بإيقاع ثابت مع دفع الذراعين والساقين معاً لتنشيط كامل الجسم.", descriptionEn: "Move the machine at a steady rhythm while pushing with both your arms and legs to activate your whole body." },

  // ===================== مرونة وإحماء (mobility) =====================
  { id: "cat_cow", name: "تمدد القطة والبقرة", nameEn: "Cat-cow stretch", muscle: "mobility", type: "mobility", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: [], icon: "Wind", description: "على وضعية الزحف، قوّس ظهرك للأعلى ثم للأسفل بالتناوب مع التنفس ببطء.", descriptionEn: "On all fours, arch your back up then down alternately while breathing slowly." },
  { id: "hip_flexor_stretch", name: "تمدد ثنيات الورك", nameEn: "Hip flexor stretch", muscle: "mobility", type: "mobility", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: [], icon: "Wind", description: "اركع بركبة واحدة وادفع الوركين للأمام برفق حتى تشعر بتمدد أمام الفخذ الخلفي، ثم بدّل الجانب.", descriptionEn: "Kneel on one knee and gently push your hips forward until you feel a stretch in front of your rear thigh, then switch sides." },
  { id: "shoulder_rolls", name: "لفّ الأكتاف", nameEn: "Shoulder rolls", muscle: "mobility", type: "mobility", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: [], icon: "Wind", description: "ارفع كتفيك ولفّهما للخلف ثم للأمام ببطء لتحرير توتر الرقبة والكتفين.", descriptionEn: "Raise your shoulders and roll them backward then forward slowly to release tension in the neck and shoulders." },
  { id: "quad_stretch", name: "تمدد الفخذ الأمامي", nameEn: "Standing quad stretch", muscle: "mobility", type: "mobility", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: ["knee"], icon: "Wind", description: "قف على رجل واحدة واسحب كعب الرجل الأخرى نحو المؤخرة برفق، ثم بدّل.", descriptionEn: "Stand on one leg and gently pull the heel of the other leg toward your glutes, then switch." },
  { id: "worlds_greatest_stretch", name: "التمدد الشامل", nameEn: "World's greatest stretch", muscle: "mobility", type: "mobility", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "intermediate", joints: [], icon: "Wind", description: "خطِ خطوة واسعة للأمام وضع يدك على الأرض، ثم لُف جذعك ومدّ ذراعك الأخرى للأعلى، وبدّل الجانب.", descriptionEn: "Take a wide step forward and place your hand on the ground, then rotate your torso and extend your other arm upward." },
  { id: "neck_stretch", name: "تمدد الرقبة", nameEn: "Neck stretch", muscle: "mobility", type: "mobility", equipment: ["gym", "home_full_equipment", "home_light_weights", "home_no_equipment"], difficulty: "beginner", joints: [], icon: "Wind", description: "أمل رأسك برفق نحو كتف واحدة حتى تشعر بتمدد جانب الرقبة، ثم بدّل الجانب.", descriptionEn: "Gently tilt your head toward one shoulder until you feel a stretch on the side of your neck, then switch sides." },
];

// ملاحظة: ندعم الآن أيضاً `gym` مع بيئتي المنزل (home_full_equipment/
// home_light_weights) كتوسّع طبيعي، بينما home_no_equipment يبقى مقتصراً
// على تمارين وزن الجسم الحقيقية فقط - لا حاجة لأي تحقّق إضافي هنا، القائمة
// أعلاه صحيحة بذاتها.

export function youtubeSearchUrl(exercise, lang = "ar") {
  const name = lang === "en" ? (exercise.nameEn || exercise.name) : exercise.name;
  const query = encodeURIComponent(`${name} exercise tutorial`);
  return `https://www.youtube.com/results?search_query=${query}`;
}
