export const S = {
  app: { minHeight: "100vh", background: "var(--bg)", color: "var(--ink)" },
  header: { position: "sticky", top: 0, background: "rgba(10,10,11,0.95)", backdropFilter: "blur(10px)", borderBottom: "1px solid var(--line)", zIndex: 20, maxWidth: 480, margin: "0 auto", padding: "16px 18px 0" },
  headerTop: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  brand: { display: "flex", alignItems: "center", gap: 8 },
  brandMark: { color: "var(--gold)", fontSize: 19 },
  brandText: { fontFamily: "'Amiri', serif", fontSize: 22, fontWeight: 700 },
  headerStats: { display: "flex", gap: 8, alignItems: "center" },
  cloudDot: { fontSize: 10, padding: "3px 8px", borderRadius: 20, fontWeight: 700 },
  hStat: { display: "flex", alignItems: "center", gap: 4, fontSize: 12.5, color: "#B8B5AF", background: "#141416", border: "1px solid #1F1F22", borderRadius: 20, padding: "4px 10px", fontVariantNumeric: "tabular-nums" },
  tabs: { display: "flex", gap: 2, overflowX: "auto" },
  tabBtn: { flex: "1 0 auto", display: "flex", flexDirection: "column", alignItems: "center", gap: 3, padding: "8px 10px", border: "none", borderBottom: "2px solid transparent", background: "transparent", color: "#7A776F", fontSize: 11, fontFamily: "inherit", fontWeight: 600, cursor: "pointer", transition: "all 0.15s" },
  tabBtnActive: { color: "var(--gold)", borderBottom: "2px solid var(--gold)" },
  body: { maxWidth: 480, margin: "0 auto" },
  view: { padding: "18px 18px 40px" },

  dateRow: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 16 },
  dateLabel: { fontSize: 14, color: "#B8B5AF", display: "flex", alignItems: "center", gap: 8 },
  todayPill: { background: "rgba(201,162,75,0.13)", color: "var(--gold)", fontSize: 10, padding: "2px 8px", borderRadius: 20, fontWeight: 700 },
  iconBtn: { background: "#161618", border: "1px solid #1F1F22", borderRadius: 8, color: "#B8B5AF", width: 32, height: 32, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" },

  wheelSection: { display: "flex", justifyContent: "center", position: "relative", marginBottom: 8 },
  periodToggle: { display: "flex", alignItems: "center", gap: 6, border: "1px solid var(--line)", borderRadius: 20, padding: "6px 16px", fontSize: 12.5, fontWeight: 700, cursor: "pointer", fontFamily: "inherit", background: "var(--panel)", transition: "background 0.5s ease, border-color 0.5s ease, color 0.5s ease" },
  periodToggleMorning: { color: "#C9A24B", borderColor: "rgba(201,162,75,0.4)", background: "rgba(201,162,75,0.08)" },
  periodToggleEvening: { color: "#7FAEEE", borderColor: "rgba(94,150,224,0.4)", background: "rgba(94,150,224,0.08)" },
  legendRow: { display: "flex", flexWrap: "wrap", gap: 8, justifyContent: "center", marginBottom: 18 },
  legendChip: { display: "flex", alignItems: "center", gap: 6, fontSize: 12, color: "#B8B5AF", background: "#141416", border: "1px solid #1F1F22", borderRadius: 20, padding: "5px 10px" },
  legendDot: { width: 8, height: 8, borderRadius: "50%", display: "inline-block", flexShrink: 0 },
  legendMins: { color: "var(--muted)", fontSize: 11 },
  emptyHint: { color: "var(--muted)", fontSize: 13, textAlign: "center", padding: "12px 0" },

  evolutionCard: { background: "linear-gradient(160deg, #15130E, #121214)", border: "1px solid #2A2418", borderRadius: 16, padding: "14px", marginBottom: 20 },
  evolutionHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  evolutionTitleRow: { display: "flex", alignItems: "center", gap: 7 },
  evolutionTitle: { fontFamily: "'Amiri', serif", fontSize: 16, fontWeight: 700 },
  evolutionBtn: { display: "flex", alignItems: "center", gap: 5, background: "rgba(201,162,75,0.09)", border: "1px solid rgba(201,162,75,0.27)", color: "var(--gold)", borderRadius: 8, padding: "6px 12px", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" },
  evolutionEmpty: { fontSize: 12.5, color: "#8A8782", lineHeight: 1.7 },
  moodPill: { display: "inline-block", background: "rgba(201,162,75,0.13)", color: "var(--gold)", fontSize: 11, fontWeight: 700, padding: "3px 12px", borderRadius: 20, marginBottom: 10 },
  evolutionSummary: { fontSize: 13.5, color: "#D8D5CF", lineHeight: 1.8, margin: "0 0 10px" },
  tipBox: { display: "flex", alignItems: "flex-start", gap: 8, background: "rgba(95,168,160,0.08)", border: "1px solid rgba(95,168,160,0.2)", borderRadius: 10, padding: "9px 11px", fontSize: 12.5, color: "#A8D5CF", lineHeight: 1.6 },

  entryListHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  addBtn: { display: "flex", alignItems: "center", gap: 6, background: "var(--gold)", color: "var(--bg)", border: "none", borderRadius: 10, padding: "8px 14px", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" },
  entryList: { display: "flex", flexDirection: "column", gap: 8, marginBottom: 16 },
  entryRow: { display: "flex", alignItems: "center", gap: 10, background: "var(--panel)", border: "1px solid var(--line)", borderRadius: 12, padding: "10px 12px", cursor: "pointer" },
  entryRowActive: { borderColor: "#3A3530" },
  entryBar: { width: 4, height: 32, borderRadius: 3, flexShrink: 0 },
  entryInfo: { flex: 1, minWidth: 0 },
  entryName: { fontSize: 13.5, fontWeight: 600 },
  entryNote: { fontSize: 12, color: "var(--muted)", marginTop: 2 },
  entryTime: { textAlign: "left", fontSize: 11.5, color: "#8A8782", whiteSpace: "nowrap" },
  entryDuration: { color: "var(--gold)", marginTop: 2, fontWeight: 600 },
  deleteBtn: { background: "none", border: "none", color: "#4A4845", cursor: "pointer", padding: 8, display: "flex", alignItems: "center", justifyContent: "center" },
  emptyState: { textAlign: "center", padding: "30px 0", color: "var(--muted)" },
  emptyStateTitle: { fontSize: 14, fontWeight: 600, color: "#8A8782" },
  emptyStateSub: { fontSize: 12, marginTop: 4 },

  quickTasks: { background: "var(--panel)", border: "1px solid var(--line)", borderRadius: 14, padding: "12px 14px" },
  quickTasksTitle: { fontSize: 12, fontWeight: 700, color: "var(--muted)", marginBottom: 10 },
  quickTaskRow: { display: "flex", alignItems: "center", gap: 10, padding: "5px 0", cursor: "pointer" },
  quickTaskText: { fontSize: 13, color: "#D8D5CF" },
  quickTaskTextDone: { color: "#5A5650", textDecoration: "line-through" },

  sectionTitle: { fontFamily: "'Amiri', serif", fontSize: 20, fontWeight: 700, marginBottom: 14 },

  taskComposer: { display: "flex", gap: 8, marginBottom: 10 },
  taskInput: { flex: 1, background: "#0F0F11", border: "1px solid #2A2A2D", borderRadius: 12, padding: "12px 14px", color: "var(--ink)", fontSize: 14, fontFamily: "inherit" },
  taskAddBtn: { background: "var(--gold)", color: "var(--bg)", border: "none", borderRadius: 12, width: 46, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flexShrink: 0 },
  taskMeta: { display: "flex", gap: 8, marginBottom: 16, alignItems: "center" },
  catScroll: { display: "flex", gap: 6, overflowX: "auto", flex: 1, paddingBottom: 2 },
  catMini: { display: "flex", alignItems: "center", gap: 5, border: "1px solid #2A2A2D", borderRadius: 20, padding: "5px 10px", fontSize: 11.5, color: "#D8D5CF", cursor: "pointer", fontFamily: "inherit", whiteSpace: "nowrap", flexShrink: 0 },
  dateInput: { background: "#0F0F11", border: "1px solid #2A2A2D", borderRadius: 10, padding: "7px 10px", color: "var(--ink)", fontSize: 12, fontFamily: "inherit", flexShrink: 0 },
  filterRow: { display: "flex", gap: 6, marginBottom: 14 },
  filterBtn: { background: "transparent", border: "1px solid #1F1F22", borderRadius: 20, padding: "6px 14px", fontSize: 12.5, color: "#8A8782", cursor: "pointer", fontFamily: "inherit", fontWeight: 600 },
  filterBtnActive: { background: "#161618", color: "var(--ink)", borderColor: "#2A2A2D" },
  taskList: { display: "flex", flexDirection: "column", gap: 8 },
  taskRow: { display: "flex", alignItems: "flex-start", gap: 10, background: "var(--panel)", border: "1px solid var(--line)", borderRadius: 12, padding: "11px 12px" },
  checkbox: { width: 24, height: 24, borderRadius: 7, border: "1.5px solid #3A3835", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "var(--bg)", flexShrink: 0, marginTop: 1 },
  checkboxDone: { background: "#5FA8A0", borderColor: "#5FA8A0" },
  taskInfo: { flex: 1, minWidth: 0 },
  taskTitle: { fontSize: 14, color: "var(--ink)", marginBottom: 4 },
  taskTitleDone: { color: "#5A5650", textDecoration: "line-through" },
  taskTags: { display: "flex", gap: 8, flexWrap: "wrap" },
  taskTag: { display: "flex", alignItems: "center", gap: 4, fontSize: 11, color: "#7A776F" },

  reportsHead: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 },
  rangeToggle: { display: "flex", gap: 4, background: "#141416", borderRadius: 10, padding: 3 },
  rangeBtn: { background: "transparent", border: "none", borderRadius: 8, padding: "6px 14px", fontSize: 12.5, color: "#8A8782", cursor: "pointer", fontFamily: "inherit", fontWeight: 600 },
  rangeBtnActive: { background: "var(--gold)", color: "var(--bg)" },
  kpiRow: { display: "flex", gap: 10, marginBottom: 16 },
  kpiCard: { flex: 1, background: "var(--panel)", border: "1px solid var(--line)", borderRadius: 12, padding: "14px 10px", textAlign: "center" },
  kpiValue: { fontFamily: "'Amiri', serif", fontSize: 18, fontWeight: 700, color: "var(--gold)" },
  kpiLabel: { fontSize: 11, color: "var(--muted)", marginTop: 4 },
  chartCard: { background: "var(--panel)", border: "1px solid var(--line)", borderRadius: 14, padding: "14px 12px", marginBottom: 14 },
  chartTitle: { fontSize: 13, fontWeight: 600, color: "#B8B5AF", marginBottom: 8, paddingRight: 4 },
  detailLine: { fontSize: 11.5, color: "#8A8782", marginTop: 8, textAlign: "center" },
  pieRow: { display: "flex", alignItems: "center", gap: 10 },
  pieLegend: { display: "flex", flexDirection: "column", gap: 6, flex: 1 },

  reportDot: { color: "var(--gold)", flexShrink: 0 },

  badgesCard: { background: "var(--panel)", border: "1px solid var(--line)", borderRadius: 14, padding: "14px 12px", marginBottom: 16 },
  badgesGrid: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 10 },
  badge: { background: "#0F0F11", border: "1px solid var(--line)", borderRadius: 12, padding: "14px 8px", textAlign: "center", opacity: 0.5 },
  badgeEarned: { opacity: 1, borderColor: "#2A2418", background: "#15130E" },
  badgeIcon: { fontSize: 22, color: "#3A3835", marginBottom: 6 },
  badgeIconEarned: { color: "var(--gold)" },
  badgeName: { fontSize: 11.5, fontWeight: 700, color: "#D8D5CF" },
  badgeDesc: { fontSize: 10, color: "var(--muted)", marginTop: 2 },

  catEditorCard: { background: "var(--panel)", border: "1px solid var(--line)", borderRadius: 14, padding: "14px 12px", marginBottom: 16 },
  catEditorHeader: { display: "flex", alignItems: "center", gap: 7, fontSize: 13, fontWeight: 700, color: "#B8B5AF", marginBottom: 12 },
  catEditList: { display: "flex", flexDirection: "column", gap: 8, marginBottom: 14 },
  catEditRow: { display: "flex", alignItems: "center", gap: 8, background: "#0F0F11", border: "1px solid var(--line)", borderRadius: 10, padding: "8px 10px", flexWrap: "wrap" },
  catEditName: { flex: 1, fontSize: 13, color: "var(--ink)" },
  catIconBtn: { background: "none", border: "none", color: "var(--muted)", cursor: "pointer", padding: 4, display: "flex" },
  catEditInput: { flex: 1, background: "#0A0A0B", border: "1px solid #2A2A2D", borderRadius: 8, padding: "8px 10px", color: "var(--ink)", fontSize: 13, fontFamily: "inherit", minWidth: 100 },
  catSaveBtn: { background: "#5FA8A0", border: "none", borderRadius: 8, color: "var(--bg)", width: 32, height: 32, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" },
  colorPickRow: { display: "flex", gap: 5, flexWrap: "wrap", width: "100%", marginBottom: 4 },
  colorDot: { width: 18, height: 18, borderRadius: "50%", border: "none", cursor: "pointer", padding: 0 },
  catAddRow: { borderTop: "1px solid var(--line)", paddingTop: 12 },
  catAddInputRow: { display: "flex", gap: 8, marginTop: 4 },

  setupCard: { background: "var(--teal)", border: "1px solid #2A4A4A", borderRadius: 14, padding: "14px", marginBottom: 16, display: "flex", gap: 10, alignItems: "flex-start" },
  setupText: { fontSize: 12.5, color: "#BFD8D4", lineHeight: 1.7 },
  linkBtn: { background: "var(--gold)", color: "var(--bg)", border: "none", borderRadius: 10, padding: "8px 14px", fontSize: 12.5, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" },

  roadmapCard: { background: "var(--panel)", border: "1px solid var(--line)", borderRadius: 14, padding: "14px 12px" },
  roadmapPhaseRow: { marginBottom: 14, paddingBottom: 14, borderBottom: "1px solid #161618" },
  roadmapPhaseHead: { display: "flex", alignItems: "center", gap: 8, marginBottom: 6 },
  roadmapPhaseTag: { fontSize: 10, fontWeight: 700, color: "var(--gold)", background: "rgba(201,162,75,0.09)", padding: "2px 8px", borderRadius: 20 },
  roadmapPhaseTitle: { fontFamily: "'Amiri', serif", fontSize: 14, fontWeight: 700 },
  roadmapPhaseItems: { display: "flex", flexDirection: "column", gap: 4 },
  roadmapPhaseItem: { display: "flex", gap: 8, fontSize: 12.5, color: "#9A968F", lineHeight: 1.6 },

  modalOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.67)", display: "flex", alignItems: "flex-end", justifyContent: "center", zIndex: 100 },
  modal: { background: "#141416", borderRadius: "20px 20px 0 0", width: "100%", maxWidth: 480, padding: "16px 18px 24px", border: "1px solid #2A2A2D", borderBottom: "none" },
  modalHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: 15, fontWeight: 700, marginBottom: 16 },
  modalBody: { display: "flex", flexDirection: "column", gap: 4 },
  label: { fontSize: 11.5, color: "var(--muted)", fontWeight: 600, marginBottom: 6, marginTop: 10 },
  catGrid: { display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 4 },
  catChip: { display: "flex", alignItems: "center", gap: 6, border: "1px solid #2A2A2D", borderRadius: 20, padding: "6px 12px", fontSize: 12.5, color: "var(--ink)", cursor: "pointer", fontFamily: "inherit" },
  timeRow: { display: "flex", gap: 10 },
  timeField: { flex: 1 },
  input: { width: "100%", background: "#0F0F11", border: "1px solid #2A2A2D", borderRadius: 10, padding: "10px 12px", color: "var(--ink)", fontSize: 14, fontFamily: "inherit" },
  saveBtn: { width: "100%", background: "var(--gold)", color: "var(--bg)", border: "none", borderRadius: 12, padding: "13px 0", fontSize: 14, fontWeight: 700, cursor: "pointer", marginTop: 18, fontFamily: "inherit" },
  toast: { position: "fixed", bottom: 20, left: "50%", transform: "translateX(-50%)", background: "#1F1F22", color: "var(--ink)", padding: "9px 18px", borderRadius: 20, fontSize: 13, border: "1px solid #2A2A2D", zIndex: 200 },
  loaderWrap: { display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh" },

  achieveHero: { display: "flex", alignItems: "center", gap: 12, marginBottom: 16 },
  achieveHeroIcon: { width: 44, height: 44, borderRadius: 14, background: "linear-gradient(140deg, #E0B868, #C9A24B)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  achieveHeroTitle: { fontFamily: "'Amiri', serif", fontSize: 24, fontWeight: 700 },
  achieveHeroSub: { fontSize: 12, color: "#8A8782", marginTop: 2, lineHeight: 1.5 },
  achieveTabs: { display: "flex", gap: 6, marginBottom: 14 },
  achieveTab: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 5, padding: "9px 0", border: "1px solid #1F1F22", borderRadius: 10, background: "transparent", color: "#8A8782", fontSize: 12.5, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" },
  achieveTabActive: { background: "#161618", color: "var(--gold)", borderColor: "#2A2A2D" },
  achieveList: { display: "flex", flexDirection: "column", gap: 10, marginTop: 4 },
  achieveCard: { background: "var(--panel)", border: "1px solid var(--line)", borderRadius: 14, padding: "14px" },
  achieveCardDone: { opacity: 0.6, borderColor: "rgba(95,168,160,0.3)" },
  achieveCardTop: { display: "flex", alignItems: "flex-start", gap: 10, marginBottom: 8 },
  achieveCardHead: { display: "flex", alignItems: "center", gap: 8, marginBottom: 4 },
  achieveKind: { fontSize: 10, fontWeight: 700, color: "var(--gold)", background: "rgba(201,162,75,0.1)", padding: "2px 8px", borderRadius: 20 },
  achieveTopic: { fontSize: 10.5, color: "#7A776F" },
  achieveTitle: { fontSize: 14.5, fontWeight: 700, color: "var(--ink)", lineHeight: 1.5 },
  achieveDetail: { fontSize: 12.5, color: "#9A968F", lineHeight: 1.7, margin: "0 0 10px" },
  achieveToggle: { display: "flex", alignItems: "center", gap: 5, background: "none", border: "none", color: "#8A8782", fontSize: 12, fontWeight: 600, cursor: "pointer", fontFamily: "inherit", padding: 0, marginBottom: 8 },
  achieveSteps: { display: "flex", flexDirection: "column", gap: 8, marginBottom: 10, paddingRight: 2 },
  achieveStep: { display: "flex", alignItems: "flex-start", gap: 8, fontSize: 12.5, color: "#C9C6C0", lineHeight: 1.6 },
  achieveStepNum: { width: 18, height: 18, borderRadius: "50%", background: "#1F1F22", color: "var(--gold)", fontSize: 10, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, marginTop: 1 },
  achieveLink: { display: "inline-flex", alignItems: "center", gap: 5, fontSize: 11.5, color: "#5FA8A0", textDecoration: "none", fontWeight: 600 },

  profileCard: { background: "linear-gradient(160deg, #15130E, #121214)", border: "1px solid #2A2418", borderRadius: 14, padding: "14px 12px", marginBottom: 16 },
  profileHint: { fontSize: 12, color: "#8A8782", lineHeight: 1.6, margin: "0 0 8px" },

  timerCard: { background: "var(--panel)", border: "1px solid var(--line)", borderRadius: 18, padding: "20px 16px", marginBottom: 16 },
  timerTime: { fontFamily: "'Amiri', serif", fontSize: 44, fontWeight: 700, color: "var(--ink)", fontVariantNumeric: "tabular-nums", lineHeight: 1 },
  timerTargetLabel: { fontSize: 12, color: "#8A8782", marginTop: 8 },
  timerControls: { display: "flex", gap: 10, marginTop: 14, alignItems: "center" },
  timerPrimary: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: "var(--gold)", color: "var(--bg)", border: "none", borderRadius: 12, padding: "14px 0", fontSize: 15, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" },
  timerSecondary: { width: 50, height: 50, display: "flex", alignItems: "center", justifyContent: "center", background: "#1A1A1D", border: "1px solid #2A2A2D", borderRadius: 12, color: "#B8B5AF", cursor: "pointer", flexShrink: 0 },
  focusStatsRow: { display: "flex", gap: 10, marginBottom: 16 },

  commitCard: { background: "var(--panel)", border: "1px solid var(--line)", borderRadius: 14, padding: "14px 12px", marginTop: 4 },
  commitList: { display: "flex", flexDirection: "column", gap: 10, marginBottom: 14 },
  commitItem: { background: "#0F0F11", border: "1px solid var(--line)", borderRadius: 12, padding: "12px" },
  commitItemTop: { display: "flex", alignItems: "flex-start", gap: 8, marginBottom: 10 },
  commitTitle: { fontSize: 14, fontWeight: 700, color: "var(--ink)" },
  commitMeta: { fontSize: 11, color: "#7A776F", marginTop: 3 },
  commitDoneBadge: { display: "flex", alignItems: "center", gap: 3, fontSize: 10.5, fontWeight: 700, color: "#5FA8A0", background: "rgba(95,168,160,0.12)", padding: "3px 8px", borderRadius: 20, flexShrink: 0, height: "fit-content" },
  commitBarWrap: { height: 7, background: "#1A1A1D", borderRadius: 4, overflow: "hidden", marginBottom: 6 },
  commitBarFill: { height: "100%", borderRadius: 4, transition: "width 0.3s" },
  commitProgress: { fontSize: 11, color: "#7A776F" },
  commitAdd: { display: "flex", gap: 8, borderTop: "1px solid var(--line)", paddingTop: 12, alignItems: "center" },
  commitSelect: { background: "#0A0A0B", border: "1px solid #2A2A2D", borderRadius: 8, padding: "9px 8px", color: "var(--ink)", fontSize: 12, fontFamily: "inherit", flexShrink: 0 },

  defaultsBtn: { display: "flex", alignItems: "center", gap: 5, background: "rgba(95,168,160,0.1)", border: "1px solid rgba(95,168,160,0.3)", borderRadius: 20, padding: "6px 12px", fontSize: 12, color: "#5FA8A0", cursor: "pointer", fontFamily: "inherit", fontWeight: 600, marginRight: "auto" },
  exportBtn: { display: "flex", alignItems: "center", justifyContent: "center", gap: 8, width: "100%", background: "transparent", border: "1px solid #2A2A2D", color: "#B8B5AF", borderRadius: 12, padding: "11px 0", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "inherit", marginBottom: 16 },

  subTabRow: { display: "flex", gap: 4, marginBottom: 16, background: "#141416", borderRadius: 12, padding: 4 },
  subTab: { flex: "1 1 0", minWidth: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 3, padding: "8px 4px", border: "none", borderRadius: 9, background: "transparent", color: "#8A8782", fontSize: 11, fontWeight: 600, cursor: "pointer", fontFamily: "inherit", textAlign: "center", lineHeight: 1.3 },
  subTabActive: { background: "#1F1F22", color: "var(--gold)" },

  adjustRow: { display: "flex", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 18 },
  adjustBtn: { background: "rgba(201,162,75,0.1)", border: "1px solid rgba(201,162,75,0.3)", color: "var(--gold)", borderRadius: 10, padding: "8px 14px", fontSize: 14, fontWeight: 700, cursor: "pointer", fontFamily: "inherit", fontVariantNumeric: "tabular-nums" },
  adjustBtnSmall: { background: "transparent", border: "1px solid #2A2A2D", color: "#B8B5AF", borderRadius: 8, padding: "7px 11px", fontSize: 12.5, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" },
  adjustValue: { fontFamily: "'Amiri', serif", fontSize: 18, fontWeight: 700, color: "var(--ink)", minWidth: 54, textAlign: "center" },
  studyToggleRow: { display: "flex", gap: 8, marginTop: 14 },
  studyToggle: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 6, background: "transparent", border: "1px solid #2A2A2D", borderRadius: 10, padding: "9px 0", fontSize: 12.5, color: "#8A8782", cursor: "pointer", fontFamily: "inherit", fontWeight: 600 },
  studyToggleActive: { background: "rgba(95,168,160,0.1)", borderColor: "rgba(95,168,160,0.4)", color: "#5FA8A0" },
  memoryNote: { display: "flex", gap: 8, alignItems: "flex-start", background: "#0F0F11", border: "1px solid var(--line)", borderRadius: 10, padding: "10px 12px", fontSize: 11.5, color: "#8A8782", lineHeight: 1.6, marginBottom: 16, marginTop: 12 },

  sessionLog: { display: "flex", flexDirection: "column", gap: 6 },
  sessionRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 12.5, padding: "6px 0", borderBottom: "1px solid #161618" },
  sessionLabel: { flex: 1, color: "#C9C6C0", minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  sessionMins: { color: "var(--gold)", fontWeight: 600, fontVariantNumeric: "tabular-nums" },
  sessionDate: { color: "#6B6863", fontSize: 11, fontVariantNumeric: "tabular-nums", minWidth: 48, textAlign: "left" },

  rankBanner: { display: "flex", alignItems: "center", gap: 8, background: "var(--panel)", border: "1px solid var(--line)", borderRadius: 12, padding: "12px 14px", fontSize: 13, color: "#B8B5AF", marginBottom: 14 },
  leadPill: { marginRight: "auto", background: "rgba(201,162,75,0.12)", color: "var(--gold)", fontSize: 10.5, fontWeight: 700, padding: "3px 10px", borderRadius: 20 },
  botsList: { display: "flex", flexDirection: "column", gap: 8 },
  botRow: { display: "flex", alignItems: "center", gap: 10, background: "var(--panel)", border: "1px solid var(--line)", borderRadius: 12, padding: "12px" },
  botRowMe: { borderColor: "rgba(201,162,75,0.4)", background: "linear-gradient(160deg, #15130E, #121214)" },
  botRank: { fontFamily: "'Amiri', serif", fontSize: 16, fontWeight: 700, color: "#6B6863", width: 20, textAlign: "center", flexShrink: 0 },
  botEmoji: { fontSize: 18, flexShrink: 0 },
  botInfo: { flex: 1, minWidth: 0 },
  botName: { fontSize: 13, fontWeight: 700, color: "var(--ink)", marginBottom: 2 },
  botYou: { background: "rgba(201,162,75,0.12)", color: "var(--gold)", fontSize: 10, padding: "1px 6px", borderRadius: 10, marginRight: 5 },
  botTrait: { fontSize: 11, color: "#6B6863", marginBottom: 6 },
  botBarWrap: { height: 5, background: "#1A1A1D", borderRadius: 3, overflow: "hidden" },
  botBarFill: { height: "100%", borderRadius: 3, transition: "width 0.5s" },
  botMins: { fontSize: 12.5, fontWeight: 700, color: "var(--gold)", fontVariantNumeric: "tabular-nums", flexShrink: 0 },

  smartBanner: { display: "flex", alignItems: "center", gap: 8, background: "rgba(201,162,75,0.06)", border: "1px solid rgba(201,162,75,0.2)", borderRadius: 10, padding: "9px 12px", fontSize: 12, color: "#C9A24B", marginBottom: 14 },
  coachCard: { background: "linear-gradient(160deg, #15130E, #121214)", border: "1px solid #2A2418", borderRadius: 16, padding: "14px", marginBottom: 16 },
  coachTitleRow: { display: "flex", alignItems: "center", gap: 7, marginBottom: 6 },
  coachTitle: { fontFamily: "'Amiri', serif", fontSize: 16, fontWeight: 700 },
  moodRow: { display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 10 },
  moodBtn: { background: "#141416", border: "1px solid #2A2A2D", borderRadius: 20, padding: "7px 14px", fontSize: 12.5, color: "#D8D5CF", cursor: "pointer", fontFamily: "inherit", fontWeight: 600 },
  coachLoading: { display: "flex", alignItems: "center", gap: 8, fontSize: 12.5, color: "#8A8782", marginTop: 8 },
  coachReply: { background: "rgba(255,255,255,0.03)", border: "1px solid #2A2A2D", borderRadius: 12, padding: "12px", marginTop: 8 },
  coachMessage: { fontSize: 13, color: "#D8D5CF", lineHeight: 1.7, marginBottom: 8 },
  coachActivity: { display: "flex", alignItems: "center", gap: 7, fontSize: 13, fontWeight: 700, color: "var(--gold)", marginBottom: 6 },
  coachWhy: { fontSize: 12, color: "#8A8782", lineHeight: 1.6 },
};
